name: Pulumi Preview (Stg PullRequest)

on:
  pull_request:
    branches:
      - stg

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/kronos
    steps:
      - name: CheckOut üõéÔ∏è
        uses: actions/checkout@v3

      - name: Setup Node ‚ú®
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Npm Install üì¶Ô∏è
        run: npm install

      - name: Authenticate to Google Cloud üîë
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.GCP_PROJECT_ID_STG }}
          export_default_credentials: true

      - name: Preview Pulumi üöÄ
        uses: pulumi/actions@v4
        with:
          command: preview
          stack-name: stg
          work-dir: infra/kronos
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GOOGLE_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID_STG }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
